apiVersion: kdex.dev/v1alpha1
kind: KDexTheme
metadata:
  name: kdex-main-site-theme
  namespace: kdex-site
spec:
  assets:
    - linkHref: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@latest/css/all.min.css
      attributes:
        rel: preload
        as: style
        onload: this.onload=null;this.rel='stylesheet'
    - linkHref: /assets/main.css
      attributes:
        rel: stylesheet
    - linkHref: /assets/images/KDex-Gear-Icon-Only.svg
      attributes:
        rel: icon
        type: image/svg+xml
  image: k3d-registry:5000/kdex-tech/kdex-main-site-theme
  pullPolicy: Always
  ingressPath: /assets
  scriptLibraryRef:
    kind: KDexScriptLibrary
    name: kdex-main-site-scriptlib
