apiVersion: kdex.dev/v1alpha1
kind: KDexHost
metadata:
  name: kdex-tech
  namespace: kdex-site
spec:
  brandName: KDex Tech
  organization: KDex Tech Inc.
  defaultLang: en
  routing:
    domains:
      - local.kdex.test
      - www.local.kdex.test
  defaultThemeRef:
    kind: KDexTheme
    name: kdex-main-site-theme