apiVersion: kdex.dev/v1alpha1
kind: KDexPageBinding
metadata:
  name: page-main
  namespace: kdex-site
spec:
  basePath: /
  contentEntries:
    - rawHTML: |
        <h1>Welcome to KDex Tech</h1>
        <p>The future of Cloud Native Application Servers is here.</p>
      slot: main
  hostRef:
    name: kdex-tech
  label: Home
  navigationHints:
    weight: 0
  pageArchetypeRef:
    kind: KDexClusterPageArchetype
    name: kdex-default-page-archetype
