apiVersion: kdex.dev/v1alpha1
kind: KDexPageBinding
metadata:
  name: page-docs
  namespace: kdex-site
spec:
  basePath: /docs
  contentEntries:
    - rawHTML: |
        <h1>Documentation</h1>
        <p>Find everything you need to get started with KDex.</p>
      slot: main
  hostRef:
    name: kdex-tech
  label: Documentation
  navigationHints:
    weight: 200
  pageArchetypeRef:
    kind: KDexClusterPageArchetype
    name: kdex-default-page-archetype
